---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared-access
  name: access1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-access
      tunnel-access: access1
  template:
    metadata:
      labels:
        app: cloudflared-access
        tunnel-access: access1
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2022.1.3
        env:
        - name: HOSTNAME
          value: example1.zeeweb.xyz
        args:
        - access
        - tcp
        - --hostname
        - $(HOSTNAME)
        - --url
        - 0.0.0.0:10000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudflared-access
  name: access1
spec:
  type: ClusterIP
  ports:
  - name: access
    port: 10000
    protocol: TCP
  selector:
    app: cloudflared-access
    tunnel-access: access1
