
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tunnel.zeeweb.xyz
  resources:
  - tunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tunnel.zeeweb.xyz
  resources:
  - tunnels/finalizers
  verbs:
  - update
- apiGroups:
  - tunnel.zeeweb.xyz
  resources:
  - tunnels/status
  verbs:
  - get
  - patch
  - update
