apiVersion: tunnel.zeeweb.xyz/v1alpha1
kind: Tunnel
metadata:
  name: example1
spec:
  name: example1
  # output secret.
  # cloudflared credentials.json and config.yaml will be created in this secret
  # secret:
  #   name: mysecret
  #   namepsace: mynamespace
  run: true
  ingress:
  - hostname: example1.zeeweb.xyz
    service: tcp://localhost:10000
  - hostname: kd.zeeweb.xyz
    service: https://kubernetes.default
  # - hostname: example12.zeeweb.xyz
  #   service: tcp://localhost:10000
